name: ci

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "jacobneiltaylor/personal-builder"
          install: true
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: "extauthz-cfzt:latest"
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}
